#!/usr/bin/env bash
# Bspwm configuration file:

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Polybar launch
$HOME/.config/polybar/colorblocks/launch.sh &

# wallpaper with feh
feh --bg-fill $HOME/Pictures/Wallpapers/1920x1080/landscape-winter.jpg &

# dunst is a lightweight replacement for the notification-daemons provided by most desktop environments.
dunst \
-geom "280x50-10+42" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# picom
picom -b &

# unclutter hide cursor when you do not need it.
unclutter &

# xrandr Multi Monitors
# --- Workspaces --->
workspaces() {
    name=1
    for monitor in `bspc query -M`; do
        bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
        let name++
    done
}
workspaces

bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII

bspc config border_width              1.75
bspc config window_gap                12
bspc config bottom_padding            5

bspc config split_ratio               0.52
bspc config borderless_monocle        true
bspc config single_monocle 	          true
bspc config ignore_ewmh_focus	      true

# Mouse config
bspc config pointer_modifier          mod1
bspc config click_to_focus            true
bspc config focus_follows_pointer     true
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

# Desactive mouse sleep
xsetroot -cursor_name left_ptr &

# Set the border colors.
bspc config normal_border_color       "#282C34"
bspc config active_border_color       "#282c34"
bspc config focused_border_color      "#77DF80"
bspc config presel_feedback_color     "#282C34"

# --- Window rules --->

# remove all rules first
bspc rule -r *:*

# 1 > terminal emulator
bspc rule -a kitty desktop='^1' follow=on focus=on
bspc rule -a Alacritty desktop='^1' follow=on focus=on

# 2 > web
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a opera desktop='^2' follow=on focus=on
bspc rule -a brave desktop='^2' follow=on focus=on

# 3 > files
declare -a files=(Pcmanfm Thunar qBittorrent Org.gnome.Nautilus)
for i in ${files[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on
done

# 4 > code and editor
declare -a code=(code Geany)
for i in ${code[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=one
done

# 5 > office and docs
declare -a office=(Gucharmap Atril Evince\
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on
done

# 6 > communication
declare -a communicate=(Thunderbird TelegramDesktop Hexchat Discord)
for i in ${communicate[@]}; do
    bspc rule -a $i desktop='^6' follow=on focus=on
done

# 7 > media
declare -a media=(Music MPlayer Lxmusic Inkscape Gimp obs Krita)
for i in ${media[@]}; do
    bspc rule -a $i desktop='^7' state=floating follow=on focus=on
done

# 8 > settings
bspc rule -a Virt-manager desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
Pavucontrol System-config-printer.py)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^8' state=floating follow=on focus=on
done

# custom rules
declare -a floating=(alacritty-float Pcmanfm feh gthumb Viewior'Firefox:Places')
for i in ${floating[@]}; do
    bspc rule -a $i state=floating follow=on focus=on
done

bspc rule -a Conky state=floating manage=off
