#! /bin/sh
# Bspwm configuration file:

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Polybar launch
$HOME/.config/polybar/launch.sh &

# wallpaper
feh --bg-fill /home/alphalawless/Pictures/Wallpapers/wolf.jpg &

# dunst
dunst & 

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width              1.75
bspc config window_gap                12
bspc config bottom_padding            5

bspc config split_ratio               0.52
bspc config borderless_monocle        true
bspc config single_monocle 	          true
bspc config ignore_ewmh_focus	        true

# Mouse config
bspc config pointer_modifier          mod1
bspc config click_to_focus            true
bspc config focus_follows_pointer     true
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

# Set the border colors.
bspc config normal_border_color       "#282C34"  # window not active
bspc config active_border_color       "#98C379" # ?
bspc config focused_border_color      "#282C34" # window active
bspc config presel_feedback_color     "#77DF80" # ?

# Custom rules
bspc rule -a kitty desktop='^1' state=tiled follow=on
bspc rule -a discord desktop='^4' state=tiled follow=on focus=on
bspc rule -a Gimp desktop='^5' state=tiled follow=on focus=on
bspc rule -a steam desktop='^4' state=tiled follow=on
