#!/usr/bin/env bash

# --- Bspwm configuration file --->

# --- Environment --->
export PATH="${PATH}:$HOME/.config/bspwm/bin"

# --- Colors from .Xresources --->
xrdb ~/.Xresources
colors() {
    # Variables
    FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
colors

# xrandr Multi Monitors
# --- Workspaces --->
workspaces() {
    name=1
    for monitor in `bspc query -M`; do
        bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' ''
        let name++
    done
}
workspaces

bspc config border_width              1
bspc config window_gap                10
bspc config bottom_padding            5

bspc config split_ratio               0.50
bspc config borderless_monocle        true
bspc config single_monocle 	          false
bspc config ignore_ewmh_focus	      true
bspc config click_to_focus            true
bspc config focus_follows_pointer     true

# Set the border colors.
bspc config normal_border_color       "$BACKGROUND"
bspc config active_border_color       "$MAGENTA"
bspc config focused_border_color      "$BLUE"
bspc config presel_feedback_color     "$GREEN"

# Mouse config
bspc config pointer_modifier          mod1
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

# Fix cursor
xsetroot -cursor_name left_ptr &

# --- Window rules --->

# remove all rules first
bspc rule -r *:*

# 1 > terminal emulator
bspc rule -a kitty desktop='^1' follow=on focus=on
bspc rule -a Alacritty desktop='^1' follow=on focus=on

# 2 > web
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a opera desktop='^2' follow=on focus=on
bspc rule -a brave desktop='^2' follow=on focus=on

# 3 > files
declare -a files=(Pcmanfm Thunar qBittorrent Org.gnome.Nautilus)
for i in ${files[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on
done

# 4 > code and editor
declare -a code=(code Geany)
for i in ${code[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=one
done

# 5 > office and docs
declare -a office=(Gucharmap Atril Evince\
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on
done

# 6 > communication
declare -a communicate=(Thunderbird TelegramDesktop Hexchat Discord)
for i in ${communicate[@]}; do
    bspc rule -a $i desktop='^6' follow=on focus=on
done

# 7 > media
declare -a media=(Music MPlayer Lxmusic Inkscape Gimp obs Krita)
for i in ${media[@]}; do
    bspc rule -a $i desktop='^7' state=floating follow=on focus=on
done

# 8 > settings
bspc rule -a Virt-manager desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
Pavucontrol System-config-printer.py)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^8' state=floating follow=on focus=on
done

# custom rules
declare -a floating=(alacritty-float Pcmanfm Thunar feh gthumb Viewnior Yad 'Firefox:Places')
for i in ${floating[@]}; do
    bspc rule -a $i state=floating follow=on focus=on
done

bspc rule -a Conky state=floating manage=off

# --- Inicialization --->

# kill if already running
killall -9 sxhkd dunst xsettingsd xfce4-power-manager

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# wallpaper with feh
bash $HOME/.fehbg

# Power management
xfce4-power-manager &

# unclutter hide cursor when you do not need it.
unclutter &

# Scripts bsp
bspcolors
bspbar
bspcomp
bspfloat &

